#cloud-config
bootcmd:
  - [ "cloud-init-per", "once", "amazon-linux-extras-docker",   "amazon-linux-extras", "install", "docker"      ]
  - [ "cloud-init-per", "once", "amazon-linux-extras-epel",     "amazon-linux-extras", "install", "epel"        ]
  - [ "cloud-init-per", "once", "install-pip",                  "yum", "-y", "install", "python2-pip"           ]
  - [ "cloud-init-per", "once", "install-pip-packages",         "pip", "install", "docker", "boto3", "requests" ]
#repo_update: true
#repo_upgrade: all
final_message: "The system is finally up, after $UPTIME seconds"
output:
  all: "| tee -a /var/log/cloud-init-output.log"
write_files:
  - path: /etc/cron.hourly/docker-prune.sh
    content: |
      #!/bin/sh
      docker image prune -f > /dev/null
      docker container prune -f > /dev/null
    owner: root:root
    permissions: "0700"
  - path: /etc/cron.daily/docker-prune.sh
    content: |
      #!/bin/sh
      docker image prune --all -f > /dev/null
      docker network prune -f > /dev/null
      docker volume prune -f > /dev/null
    owner: root:root
    permissions: "0700"
  - path: /etc/cron.daily/system-update.sh
    content: |
      #!/bin/sh
      yum update --assumeyes
      rm -rf /var/cache/yum
    owner: root:root
    permissions: "0700"
groups:
  - docker
users:
  - name: admin
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmETGaY8S7I6I+6Rm0rVtWwlpmOQ+ZnywQpAKyj5gnK2a/9bwSJzMt/DI+/WBodSHLfXef8P0CHfPpMKqTAN1c4kDNqNgsvAMC6lSXofqnSu4mEhEWRSsJwA8NXanQ9ph970aaQKdj+GlS9lsoMel/cOdjyPrP3RtFTd0BuAlCah5KB8Job699riVnvh6y+SyqwWtNRAesAfQqrBzLs3LTWtltqG4UZ0mkuLpVu7RbJOh1hAPqhd1NKHMjPpBXUjABMVya0qFFbq2j9W016P0dMkZO/jZqLdd6MeF25q9lNeJXU6/w5d3qSljpq9u+AbhIoUgTZerLcN2hqVWZlpDn geusebio@roosevelt